services:
  frontend:
    build: ./site
    restart: unless-stopped
    container_name: compare-frontend
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - "./site:/app"
    ports:
      - 3000:3000

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
